version: '2'

services:
  ubuntu:
      build: ubuntu
      ports:
        - "9280:80"
        - "9888:8888"

  elasticsearch:
      build: elasticsearch/
      volumes:
        - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      ports:
        - "9200:9200"
        - "9300:9300"
      environment:
        ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      networks:
        - elk
  mysql:
    image: mysql
    container_name: test-mysql
    ports:
      - 6603:3306
    environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_USER=user
       - MYSQL_PASSWORD=password
       - MYSQL_MY_DATABASE=my-database
    volumes:
      - /data/mysql:/var/lib/mysql

  mongo:
    command: mongod
    image: mongo:3.2.0
    ports:
      - "27100:27017" # map port to none standard port, to avoid conflicts with locally installed mongodb. 
    volumes:
      - /data/mongo:/var/run/docker.sock

  web:
    build: ./web
    restart: always
    ports:
      - "5000:5000"
      - "9998:22"
    environment:
      - "DOCKER_MACHINE_IP=0.0.0.0"
    depends_on:
      - elasticsearch
networks:
  elk:
    driver: bridge
